import { TreatmentCost } from "@/types/treatment";

export const treatmentComparisonData: TreatmentCost[] = [
  {
    id: 1,
    name: "Dental Cleaning",
    description: "Professional teeth cleaning and plaque removal",
    usCost: 150,
    indiaCost: 30,
    savings: 120,
    category: "Preventive",
  },
  {
    id: 2,
    name: "Filling (per tooth)",
    description: "Composite or amalgam filling",
    usCost: 200,
    indiaCost: 40,
    savings: 160,
    category: "Preventive",
  },
  {
    id: 3,
    name: "Root Canal Treatment",
    description: "Complete root canal therapy with filling",
    usCost: 1200,
    indiaCost: 250,
    savings: 950,
    category: "Restorative",
  },
  {
    id: 4,
    name: "Crown (per tooth)",
    description: "Ceramic or porcelain crown",
    usCost: 1000,
    indiaCost: 200,
    savings: 800,
    category: "Restorative",
  },
  {
    id: 5,
    name: "Bridge Work (per span)",
    description: "Multi-tooth bridge restoration",
    usCost: 1500,
    indiaCost: 300,
    savings: 1200,
    category: "Restorative",
  },
  {
    id: 6,
    name: "Implant (per tooth)",
    description: "Dental implant with abutment and crown",
    usCost: 3000,
    indiaCost: 600,
    savings: 2400,
    category: "Implants",
  },
  {
    id: 7,
    name: "Full Mouth Implants (4 implants)",
    description: "All-on-4 implant solution with denture",
    usCost: 10000,
    indiaCost: 2000,
    savings: 8000,
    category: "Implants",
  },
  {
    id: 8,
    name: "Teeth Whitening",
    description: "Professional teeth bleaching session",
    usCost: 400,
    indiaCost: 80,
    savings: 320,
    category: "Cosmetic",
  },
  {
    id: 9,
    name: "Braces (full treatment, 2 years)",
    description: "Traditional metal braces for orthodontic correction",
    usCost: 5000,
    indiaCost: 1000,
    savings: 4000,
    category: "Orthodontics",
  },
  {
    id: 10,
    name: "Tooth Extraction",
    description: "Surgical extraction of one tooth",
    usCost: 300,
    indiaCost: 60,
    savings: 240,
    category: "Surgical",
  },
  {
    id: 11,
    name: "Bone Grafting",
    description: "Bone grafting for implant preparation",
    usCost: 500,
    indiaCost: 100,
    savings: 400,
    category: "Surgical",
  },
  {
    id: 12,
    name: "Dentures (full set)",
    description: "Complete denture set (upper or lower)",
    usCost: 1500,
    indiaCost: 300,
    savings: 1200,
    category: "Prosthetics",
  },
];
